/* +------------------------------------------------------------------------+ */
/* ////////////////////////////////////||\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ */
/* +------------------------------------------------------------------------+ */
/* |                                                                        | */
/* |                              *** GEMS ***                              | */
/* |                                                                        | */
/* +------------------------------------------------------------------------+ */
/* \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\||//////////////////////////////////// */
/* +------------------------------------------------------------------------+ */

$gems = [
	{"id" : "MISC16", "name" : "Agathe de feu", "value" : 10, "desc" : "L&rsquo;agate de feu est le nom donn&eacute; &agrave; la calc&eacute;doine lorsque celle-ci contient de fines rayures de goethite iris&eacute;e. Si la pierre est taill&eacute;e comme il convient, cette irisation prend des nuances rouges, brunes, dor&eacute;es et vertes. Les plus beaux sp&eacute;cimens d&rsquo;agate de feu sont toujours au moins en partie translucides."},
	{"id" : "MISC17", "name" : "Oeil de lynx", "value" : 15, "desc" : "L&rsquo;oeil de lynx est une labradorite (un feldspath). La labradorite est une pierre dont la teinte peut aller du gris p&acirc;le au gris sombre, avec des reflets color&eacute;s, en g&eacute;n&eacute;ral bleus, bien qu&rsquo;on en voie de toutes sortes. Dans les Royaumes, on appelle oeil de lynx la labradorite &agrave; reflets verts."},
	{"id" : "MISC18", "name" : "Pierre du soleil", "value" : 25, "desc" : "La pierre de soleil est un feldspath tr&egrave;s proche de la pierre de lune. Il serait plus juste de lui donner son vrai nom, l&rsquo;oligoclase. La pierre de soleil peut &ecirc;tre incolore ou vert tendre, et &agrave; facettes, mais il est plus courant de la trouver sous la forme arrondie d&rsquo;un cabochon qui, une fois taill&eacute;, livre des pierres pr&eacute;cieuses rec&egrave;lant des paillettes d&rsquo;un rouge (ou orange) vif dispos&eacute;es en parall&egrave;le dans un milieu incolore ; la teinte dominante est alors dor&eacute;e ou brun rouge."},
	{"id" : "MISC19", "name" : "Turquoise", "value" : 5, "desc" : "La turquoise est une aigue-marine opaque paillet&eacute;e de sombre. On la trouve dans les endroits les plus arides de tous les Royaumes. Les cavaliers incluent souvent un &eacute;clat de cette pierre dans le harnais de leur monture afin d&rsquo;attirer la bonne fortune."},
	{"id" : "MISC20", "name" : "H&eacute;liothrope", "value" : 50, "desc" : "L&rsquo;h&eacute;liotrope est un quartz verd&acirc;tre plut&ocirc;t sombre, paillet&eacute; de cristaux rouges. Neuf sur dix de ces pierres proviennent des Gal&egrave;nes, la cha&icirc;ne de montagnes de Damarie, et d&rsquo;une mine situ&eacute;e dans la Passe des H&eacute;liotropes, un col frontalier d&eacute;fendu par des gardes arm&eacute;s et des fortifications, l&rsquo;h&eacute;liotrope &eacute;tant le principal bien d&rsquo;exportation de la r&eacute;gion."},
	{"id" : "MISC21", "name" : "Larme de ciel", "value" : 40, "desc" : "La larme de ciel est le nom donn&eacute; &agrave; la tectite, roche vitreuse d&rsquo;origine c&eacute;leste (m&eacute;t&eacute;oritique) que l&rsquo;on trouve le plus souvent dans les sables d&rsquo;Anauroch et d&rsquo;autres d&eacute;serts des Royaumes."},
	{"id" : "MISC22", "name" : "Andar", "value" : 30, "desc" : "Les andars sont des pierres dures, translucides et flexibles, qui, une fois taill&eacute;es, ont des reflets rouges et verts, ou bruns et verts."},
	{"id" : "MISC23", "name" : "Jaspe", "value" : 35, "desc" : "Le jaspe est un quartz opaque, en g&eacute;n&eacute;ral brun, noir ou rouge. Il arrive tr&egrave;s rarement d&rsquo;en voir un sp&eacute;cimen bleu, ou ray&eacute; de bandes bleues. Le jaspe broy&eacute; entre dans la fabrication d&rsquo;objets et dans la composition de potions magiques qui prot&egrave;gent contre le poison."},
	{"id" : "MISC24", "name" : "Tchazar", "value" : 35, "desc" : "On donne le nom de tchazar &agrave; l&rsquo;aragonite, gemme de couleur jaune paille. Elle se pr&eacute;sente sous la forme d&rsquo;un cristal prismatique allong&eacute;. Elle est douce et fragile et a besoin d&rsquo;&ecirc;tre taill&eacute;e pour donner des gemmes facett&eacute;es."},
	{"id" : "MISC25", "name" : "Zircon", "value" : 45, "desc" : "Le zircon est un cristal tirant sur le marron que l&rsquo;on trouve dans les roches ign&eacute;es (volcaniques). Le zircon acquiert ses nuances bleu p&acirc;le apr&egrave;s avoir &eacute;t&eacute; expos&eacute; &agrave; la chaleur et taill&eacute; (en g&eacute;n&eacute;ral taille &agrave; facettes)."},
	{"id" : "MISC26", "name" : "Iole", "value" : 40, "desc" : "La iole, ou iolite (cordi&eacute;rite), est en g&eacute;n&eacute;ral surnomm&eacute;e &laquo; pierre violette &raquo;, bien que sa teinte s&rsquo;approche plut&ocirc;t du bleut&eacute;. On la pr&eacute;f&egrave;re &agrave; facettes, celles-ci mettant mieux en valeur les variations de couleur selon l&rsquo;angle de vue. Une petite iole taill&eacute;e est incolore, mais un sp&eacute;cimen plus cons&eacute;quent peut contenir des inclusions d&rsquo;un autre mat&eacute;riau tel que l&rsquo;h&eacute;matite, qui lui donnera alors les reflets dor&eacute;s d&rsquo;une pierre de soleil."},
	{"id" : "MISC27", "name" : "Pierre-de-lune", "value" : 50, "desc" : "La pierre de lune est un feldspath opaque poli jusqu&rsquo;&agrave; prendre une teinte bleut&eacute;e. Selon la l&eacute;gende, la seule vue de cette pierre force un lycanthrope &agrave; reprendre sa forme animale. Cela se peut, m&ecirc;me si jamais un t&eacute;moin s&rsquo;&eacute;tant approch&eacute; assez pr&egrave;s d&rsquo;une telle sc&egrave;ne pour attester de sa v&eacute;racit&eacute; n&rsquo;a surv&eacute;cu pour en t&eacute;moigner. Mais les pierres de lune entrent dans la pr&eacute;paration de divers sorts affectant cette mal&eacute;diction."},
	{"id" : "MISC28", "name" : "&Eacute;toile d&rsquo;eau", "value" : 80, "desc" : "Egalement appel&eacute;e tourmaline incolore, l&rsquo;&eacute;toile d&rsquo;eau est rare dans les Royaumes. Cette pierre &eacute;tant pleine d&rsquo;imperfections et d&rsquo;inclusions, seule une partie infime peut &ecirc;tre utilis&eacute;e pour la taille."},
	{"id" : "MISC29", "name" : "Zo&iuml;se", "value" : 60, "desc" : "Zo&iuml;se est le nom donn&eacute; par les sages &agrave; une vari&eacute;t&eacute; particuli&egrave;re de min&eacute;ral rare dans lequel on taille des pierres d&rsquo;un &eacute;clat &agrave; trois nuances intenses qui varient selon la lumi&egrave;re : violet, bleu et rouge ou violet, vert et rouge. De grande taille (de la taille d&rsquo;un poing ou d&rsquo;un pied), ces gemmes sont tr&egrave;s pris&eacute;es et on les trouve mont&eacute;es sur des pendentifs ou des broches."},
	{"id" : "MISC30", "name" : "Chrysob&eacute;ryl", "value" : 70, "desc" : "Le chrysob&eacute;ryl est une gemme verte, dure, transparente, &agrave; facettes. On dit qu&rsquo;elle a des liens avec les Plans Ext&eacute;rieurs, d&rsquo;o&ugrave; son utilit&eacute; lorsqu&rsquo;il s&rsquo;agit de combattre une possession d&eacute;moniaque ou des morts-vivants."},
	{"id" : "MISC31", "name" : "Diopside &eacute;toil&eacute;", "value" : 85, "desc" : "Le diopside &eacute;toil&eacute; est l&rsquo;aspect le plus pris&eacute; d&rsquo;une pierre pr&eacute;cieuse que l&rsquo;on ne trouve que rarement dans de jolies couleurs. Elle est souvent trop sombre pour &ecirc;tre belle, mais les cristaux que l&rsquo;on rencontre dans les lits des torrents de montagne ont une superbe teinte vert p&acirc;le. Les gemmes d&rsquo;un vert plus soutenu peuvent &ecirc;tre taill&eacute;es en &eacute;toiles &agrave; quatre ou six branches."},
	{"id" : "MISC32", "name" : "Shandon", "value" : 90, "desc" : "Le shandon est l&rsquo;autre nom de la natrolite dans les Royaumes ; ses fins cristaux incolores rec&egrave;lent de minuscules gemmes &agrave; facettes que l&rsquo;on brode souvent dans des voiles et des robes sur lesquels la lumi&egrave;re se refl&egrave;te alors comme de l&rsquo;eau."},
	{"id" : "MISC33", "name" : "Aigue-marine", "value" : 150, "desc" : "L&rsquo;aigue-marine est un b&eacute;ryl bleu-vert, dur et transparent. Tr&egrave;s recherch&eacute;e, on la rencontre surtout chez les tribus barbares qui parcourent la toundra du nord."},
	{"id" : "MISC34", "name" : "Grenat", "value" : 175, "desc" : "Les grenats sont des cristaux dont la couleur varie du rouge profond au violet. Une fois taill&eacute;e, cette gemme peut comporter de 12 &agrave; 24 facettes, bien que certaines puissent (rarement toutefois) en compter 36. Une rumeur voudrait qu&rsquo;existe un grenat &agrave; 48 facettes, m&ecirc;me si nul ne l&rsquo;a jamais trouv&eacute;."},
	{"id" : "MISC35", "name" : "Corail noir", "value" : 125, "desc" : "Le corail noir, &eacute;galement appel&eacute; corail de nuit, est un corail... noir, comme son nom l&rsquo;indique, qui est similaire &agrave; la peau d&rsquo;ange exception faite de la couleur. Il est incroyablement difficile &agrave; travailler et, en joaillerie, il appara&icirc;t g&eacute;n&eacute;ralement sous la forme d&rsquo;une brindille ou d&rsquo;une branche, ou taill&eacute; en cabochon (arrondi et poli)."},
	{"id" : "MISC36", "name" : "Perle", "value" : 200, "desc" : "Une perle est constitu&eacute;e de couches superpos&eacute;es d&rsquo;aragonite qui se forment lentement et laborieusement autour d&rsquo;un grain de sable pr&eacute;sent dans une hu&icirc;tre ou un autre mollusque. Le r&eacute;sultat de ce processus a un bel aspect lustr&eacute;. La plupart des perles des Royaumes sont blanches, bien qu&rsquo;il en existe des sp&eacute;cimens arc-en-ciel et m&ecirc;me noirs."},
	{"id" : "MISC37", "name" : "Sph&egrave;ne", "value" : 225, "desc" : "La sph&egrave;ne est une pierre friable (et, comme la scapre, facile &agrave; travailler, y compris par le novice) dont la couleur se situe en g&eacute;n&eacute;ral dans la gamme des verts et des jaunes. Les plus recherch&eacute;es sont d&rsquo;un superbe &eacute;meraude."},
	{"id" : "MISC38", "name" : "Opale noire", "value" : 300, "desc" : "L&rsquo;opale noire est verd&acirc;tre, paillet&eacute;e de noir et d&rsquo;or. On la trouve dans des sources chaudes. La pierre, polie, se taille en cabochon. &laquo; Noir comme une opale &raquo; est une expression assez courante dans le nord, une mani&egrave;re de compliment que l&rsquo;on d&eacute;cerne aux roublards au grand coeur."},
	{"id" : "MISC39", "name" : "Opale d&rsquo;eau", "value" : 350, "desc" : "L&rsquo;opale d&rsquo;eau est une opale incolore et transparente qui a parfois un reflet color&eacute;. Rare et pr&eacute;cieuse dans les Royaumes, elle sert &agrave; fabriquer des objets li&eacute;s &agrave; la divination."},
	{"id" : "MISC40", "name" : "Lingot de lune", "value" : 375, "desc" : "Le lingot de lune est une pierre d&rsquo;un blanc bleut&eacute; et nacr&eacute;, souvent paillet&eacute;e d&rsquo;or et de vert. Apparent&eacute;e &agrave; l&rsquo;opale de feu et &agrave; l&rsquo;opale noire, elle est &agrave; peine plus r&eacute;pandue."},
	{"id" : "MISC41", "name" : "Saphir &eacute;toil&eacute;", "value" : 2000, "desc" : "Le saphir &eacute;toil&eacute; est une variante de saphir, une vraie pierre pr&eacute;cieuse, plus translucide, avec une &eacute;toile blanche en son centre. On en voit ornant les objets qui prot&egrave;gent contre la magie."},
	{"id" : "MISC42", "name" : "Diamant", "value" : 1000, "desc" : "Le diamant est une pierre dure et transparente qui peut &ecirc;tre bleue, blanc-bleu, jaune ou rose. C&rsquo;est la plus dure de toutes les gemmes et l&rsquo;une des plus pr&eacute;cieuses. Ce sont souvent les races vivant sous terre qui trouvent les diamants dans les montagnes du nord et qui les n&eacute;gocient avec la surface."},
	{"id" : "MISC43", "name" : "&Eacute;meraude", "value" : 1500, "desc" : "Une &eacute;meraude est un b&eacute;ryl d&rsquo;un vert tr&egrave;s vif, aux ar&ecirc;tes vives elles aussi, aux lignes droites, taill&eacute;e en rectangle le plus souvent. On a l&rsquo;habitude de l&rsquo;associer &agrave; la richesse, aussi les riches l&rsquo;utilisent-ils en ornement, de pr&eacute;f&eacute;rence &agrave; toute autre pierre."},
	{"id" : "MISC44", "name" : "Larme de roi", "value" : 4000, "desc" : "La larme de roi, une pierre rare et polie, sp&eacute;cifique aux Royaumes, est parfois appel&eacute;e larme gel&eacute;e, sans doute du fait de sa forme de goutte d&rsquo;eau. Nul jusqu&rsquo;&agrave; pr&eacute;sent n&rsquo;a jamais r&eacute;ussi &agrave; en briser une. On dit que ce sont les larmes cristallis&eacute;es de rois n&eacute;cromants morts depuis longtemps. On peut voir dans chacune d&rsquo;elles ce qu&rsquo;aimait le triste roi qui les a vers&eacute;es. Leur v&eacute;ritable nature reste un myst&egrave;re, mais il va de soi que les sages les tiennent pour les plus pr&eacute;cieuses de toutes les pierres pr&eacute;cieuses."},
	{"id" : "MISC45", "name" : "Esseulite", "value" : 5000, "desc" : "L&rsquo;esseulite est une pierre iris&eacute;e dont l&rsquo;arc-en-ciel de couleurs semble fluide &agrave; la lumi&egrave;re du jour. Superbe, elle est de plus tr&egrave;s rare et sert au sort de gemme de retour, ce qui en fait l&rsquo;une des pierres les plus recherch&eacute;es des Royaumes."}
];
