/* +------------------------------------------------------------------------+ */
/* ////////////////////////////////////||\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ */
/* +------------------------------------------------------------------------+ */
/* |                                                                        | */
/* |                             *** JEWELS ***                             | */
/* |                                                                        | */
/* +------------------------------------------------------------------------+ */
/* \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\||//////////////////////////////////// */
/* +------------------------------------------------------------------------+ */

$jewels = [
	{"id" : "RING01", "name" : "Anneau", "value" : 1, "desc" : "Un anneau est une fine lanière de métal précieux. Il sert en général d'ornement. Plus rares, certains sont enchantés et permettent à quiconque les porte d'user de la magie qu'ils contiennent. Ils sont de ce fait très recherchés par les aventuriers."}, 
	{"id" : "AMUL02", "name" : "Collier", "value" : 2, "desc" : "Un collier est un bijou décoratif généralement fabriqué en argent, en or, en platine ou tout autre métal précieux, et orné de gemmes. Un collier se porte toujours autour du cou et peut être de n'importe quelle longueur."}, 
	{"id" : "RING11", "name" : "Anneau d'argent", "value" : 5, "desc" : "Un anneau est une fine lanière de métal précieux. Il sert en général d'ornement. Plus rares, certains sont enchantés et permettent à quiconque les porte d'user de la magie qu'ils contiennent. Ils sont de ce fait très recherchés par les aventuriers."}, 
	{"id" : "RING14", "name" : "Anneau de néphrite", "value" : 10, "desc" : "Un anneau est une fine lanière de métal précieux. Il sert en général d'ornement. Plus rares, certains sont enchantés et permettent à quiconque les porte d'user de la magie qu'ils contiennent. Ils sont de ce fait très recherchés par les aventuriers."}, 
	{"id" : "AMUL09", "name" : "Collier d'argent", "value" : 10, "desc" : "Un collier est un bijou décoratif généralement fabriqué en argent, en or, en platine ou tout autre métal précieux, et orné de gemmes. Un collier se porte toujours autour du cou et peut être de n'importe quelle longueur."}, 
	{"id" : "AMUL05", "name" : "Collier de roche bleue", "value" : 30, "desc" : "Un collier est un bijou décoratif généralement fabriqué en argent, en or, en platine ou tout autre métal précieux, et orné de gemmes. Un collier se porte toujours autour du cou et peut être de n'importe quelle longueur."}, 
	{"id" : "RING10", "name" : "Anneau d'or", "value" : 40, "desc" : "Un anneau est une fine lanière de métal précieux. Il sert en général d'ornement. Plus rares, certains sont enchantés et permettent à quiconque les porte d'user de la magie qu'ils contiennent. Ils sont de ce fait très recherchés par les aventuriers."}, 
	{"id" : "AMUL06", "name" : "Collier d'agni mani", "value" : 40, "desc" : "Un collier est un bijou décoratif généralement fabriqué en argent, en or, en platine ou tout autre métal précieux, et orné de gemmes. Un collier se porte toujours autour du cou et peut être de n'importe quelle longueur."}, 
	{"id" : "RING12", "name" : "Anneau d'onyx", "value" : 50, "desc" : "Un anneau est une fine lanière de métal précieux. Il sert en général d'ornement. Plus rares, certains sont enchantés et permettent à quiconque les porte d'user de la magie qu'ils contiennent. Ils sont de ce fait très recherchés par les aventuriers."}, 
	{"id" : "AMUL07", "name" : "Collier d'obsidienne arc-en-ciel", "value" : 50, "desc" : "Un collier est un bijou décoratif généralement fabriqué en argent, en or, en platine ou tout autre métal précieux, et orné de gemmes. Un collier se porte toujours autour du cou et peut être de n'importe quelle longueur."}, 
	{"id" : "AMUL08", "name" : "Collier de coquillages de porcelaine tigrée", "value" : 55, "desc" : "Un collier est un bijou décoratif généralement fabriqué en argent, en or, en platine ou tout autre métal précieux, et orné de gemmes. Un collier se porte toujours autour du cou et peut être de n'importe quelle longueur."}, 
	{"id" : "RING15", "name" : "Anneau héliotrope", "value" : 60, "desc" : "Un anneau est une fine lanière de métal précieux. Il sert en général d'ornement. Plus rares, certains sont enchantés et permettent à quiconque les porte d'user de la magie qu'ils contiennent. Ils sont de ce fait très recherchés par les aventuriers."}, 
	{"id" : "AMUL10", "name" : "Collier d'or", "value" : 60, "desc" : "Un collier est un bijou décoratif généralement fabriqué en argent, en or, en platine ou tout autre métal précieux, et orné de gemmes. Un collier se porte toujours autour du cou et peut être de n'importe quelle longueur."}, 
	{"id" : "RING13", "name" : "Anneau de jade", "value" : 80, "desc" : "Un anneau est une fine lanière de métal précieux. Il sert en général d'ornement. Plus rares, certains sont enchantés et permettent à quiconque les porte d'user de la magie qu'ils contiennent. Ils sont de ce fait très recherchés par les aventuriers."}, 
	{"id" : "RING16", "name" : "Anneau de peau d'ange", "value" : 100, "desc" : "Un anneau est une fine lanière de métal précieux. Il sert en général d'ornement. Plus rares, certains sont enchantés et permettent à quiconque les porte d'user de la magie qu'ils contiennent. Ils sont de ce fait très recherchés par les aventuriers."}, 
	{"id" : "RING17", "name" : "Anneau danse-flamme", "value" : 125, "desc" : "Un anneau est une fine lanière de métal précieux. Il sert en général d'ornement. Plus rares, certains sont enchantés et permettent à quiconque les porte d'user de la magie qu'ils contiennent. Ils sont de ce fait très recherchés par les aventuriers."}, 
	{"id" : "AMUL04", "name" : "Collier orné de gemmes zoïses", "value" : 150, "desc" : "Un collier est un bijou décoratif généralement fabriqué en argent, en or, en platine ou tout autre métal précieux, et orné de gemmes. Un collier se porte toujours autour du cou et peut être de n'importe quelle longueur."}, 
	{"id" : "RING18", "name" : "Anneau d'opale de feu", "value" : 500, "desc" : "Un anneau est une fine lanière de métal précieux. Il sert en général d'ornement. Plus rares, certains sont enchantés et permettent à quiconque les porte d'user de la magie qu'ils contiennent. Ils sont de ce fait très recherchés par les aventuriers."}, 
	{"id" : "AMUL13", "name" : "Amulette héliotrope", "value" : 500, "desc" : "Un collier est un bijou décoratif généralement fabriqué en argent, en or, en platine ou tout autre métal précieux, et orné de gemmes. Un collier se porte toujours autour du cou et peut être de n'importe quelle longueur."}, 
	{"id" : "AMUL11", "name" : "Collier de perles", "value" : 1000, "desc" : "Un collier est un bijou décoratif généralement fabriqué en argent, en or, en platine ou tout autre métal précieux, et orné de gemmes. Un collier se porte toujours autour du cou et peut être de n'importe quelle longueur."}, 
	{"id" : "RING19", "name" : "Anneau de rubis", "value" : 1750, "desc" : "Un anneau est une fine lanière de métal précieux. Il sert en général d'ornement. Plus rares, certains sont enchantés et permettent à quiconque les porte d'user de la magie qu'ils contiennent. Ils sont de ce fait très recherchés par les aventuriers."}, 
	{"id" : "AMUL12", "name" : "Collier de larmes de laérales", "value" : 6000, "desc" : "Un collier est un bijou décoratif généralement fabriqué en argent, en or, en platine ou tout autre métal précieux, et orné de gemmes. Un collier se porte toujours autour du cou et peut être de n'importe quelle longueur."}
];
