/* +------------------------------------------------------------------------+ */
/* ////////////////////////////////////||\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ */
/* +------------------------------------------------------------------------+ */
/* |                                                                        | */
/* |                             *** SOUNDS ***                             | */
/* |                                                                        | */
/* +------------------------------------------------------------------------+ */
/* \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\||//////////////////////////////////// */
/* +------------------------------------------------------------------------+ */

$sounds = [

	// ===========================================================================
	// ---------------------------------------------------------------------------
	// # Monsters
	// ---------------------------------------------------------------------------
	// ===========================================================================

	// Gibberling
	{"id" : "GIBBER01", "tag" : "gibberling", "file" : "cre/giber/giber01.mp3", "name" : "Grognement (1)"},
	{"id" : "GIBBER02", "tag" : "gibberling", "file" : "cre/giber/giber02.mp3", "name" : "Grognement (2)"},
	{"id" : "GIBBER03", "tag" : "gibberling", "file" : "cre/giber/giber03.mp3", "name" : "Rugissement (1)"},
	{"id" : "GIBBER04", "tag" : "gibberling", "file" : "cre/giber/giber04.mp3", "name" : "Rugissement (2)"},
	{"id" : "GIBBER05", "tag" : "gibberling", "file" : "cre/giber/giber05.mp3", "name" : "Attaque (1)"},
	{"id" : "GIBBER06", "tag" : "gibberling", "file" : "cre/giber/giber06.mp3", "name" : "Attaque (2)"},
	{"id" : "GIBBER08", "tag" : "gibberling", "file" : "cre/giber/giber08.mp3", "name" : "Blessure"},
	{"id" : "GIBBER09", "tag" : "gibberling", "file" : "cre/giber/giber09.mp3", "name" : "Mort"},
	// Tasloi
	{"id" : "TASLOI01", "tag" : "tasloi", "file" : "cre/taslo/taslo01.mp3", "name" : "Glapissement (1)"},
	{"id" : "TASLOI02", "tag" : "tasloi", "file" : "cre/taslo/taslo02.mp3", "name" : "Glapissement (2)"},
	{"id" : "TASLOI03", "tag" : "tasloi", "file" : "cre/taslo/taslo03.mp3", "name" : "Cri (1)"},
	{"id" : "TASLOI04", "tag" : "tasloi", "file" : "cre/taslo/taslo04.mp3", "name" : "Cri (2)"},
	{"id" : "TASLOI05", "tag" : "tasloi", "file" : "cre/taslo/taslo05.mp3", "name" : "Attaque (1)"},
	{"id" : "TASLOI06", "tag" : "tasloi", "file" : "cre/taslo/taslo06.mp3", "name" : "Attaque (2)"},
	{"id" : "TASLOI08", "tag" : "tasloi", "file" : "cre/taslo/taslo08.mp3", "name" : "Blessure"},
	{"id" : "TASLOI09", "tag" : "tasloi", "file" : "cre/taslo/taslo09.mp3", "name" : "Mort"},
	// Xvart
	{"id" : "XVART01", "tag" : "xvart", "file" : "cre/xvart/xvart01.mp3", "name" : "Saleté d'humanoïdes"},
	{"id" : "XVART02", "tag" : "xvart", "file" : "cre/xvart/xvart02.mp3", "name" : "Crevez morveux"},
	{"id" : "XVART03", "tag" : "xvart", "file" : "cre/xvart/xvart03.mp3", "name" : "Gnaaaaa-rgna"},
	{"id" : "XVART04", "tag" : "xvart", "file" : "cre/xvart/xvart04.mp3", "name" : "À l'attaque"},
	{"id" : "XVART05", "tag" : "xvart", "file" : "cre/xvart/xvart05.mp3", "name" : "Attaque (1)"},
	{"id" : "XVART06", "tag" : "xvart", "file" : "cre/xvart/xvart06.mp3", "name" : "Attaque (2)"},
	{"id" : "XVART08", "tag" : "xvart", "file" : "cre/xvart/xvart08.mp3", "name" : "Blessure"},
	{"id" : "XVART09", "tag" : "xvart", "file" : "cre/xvart/xvart09.mp3", "name" : "Mort"},
	// Bandit
	{"id" : "BANDIT01", "tag" : "bandit", "file" : "cre/bandt/bandt01.mp3", "name" : "Et alors je lui ai frappé la tête, jusqu'à ce qu'il crève."},
	{"id" : "BANDIT02", "tag" : "bandit", "file" : "cre/bandt/bandt02.mp3", "name" : "J'les détestes, ces femelettes, du Poing enflammé."},
	{"id" : "BANDIT03", "tag" : "bandit", "file" : "cre/bandt/bandt03.mp3", "name" : "Woah ! Ça c'était vraiment une cochonnerie."},
	{"id" : "BANDIT04", "tag" : "bandit", "file" : "cre/bandt/bandt04.mp3", "name" : "Arrête de te mettre les doigts dans le nez, sale garce."},
	{"id" : "BANDIT05", "tag" : "bandit", "file" : "cre/bandt/bandt05.mp3", "name" : "Blessure"},
	{"id" : "BANDIT06", "tag" : "bandit", "file" : "cre/bandt/bandt06.mp3", "name" : "Mort"},
	// Hobgoblin
	{"id" : "HOBGOB01", "tag" : "hobgoblin", "file" : "cre/hobgl/hobgl01.mp3", "name" : "Pas un mot !"},
	{"id" : "HOBGOB02", "tag" : "hobgoblin", "file" : "cre/hobgl/hobgl02.mp3", "name" : "Face de rat !"},
	{"id" : "HOBGOB03", "tag" : "hobgoblin", "file" : "cre/hobgl/hobgl03.mp3", "name" : "En avant, marche."},
	{"id" : "HOBGOB04", "tag" : "hobgoblin", "file" : "cre/hobgl/hobgl04.mp3", "name" : "N'épargnez personne."},
	{"id" : "HOBGOB05", "tag" : "hobgoblin", "file" : "cre/hobgl/hobgl05.mp3", "name" : "Attaque (1)"},
	{"id" : "HOBGOB06", "tag" : "hobgoblin", "file" : "cre/hobgl/hobgl06.mp3", "name" : "Attaque (2)"},
	{"id" : "HOBGOB07", "tag" : "hobgoblin", "file" : "cre/hobgl/hobgl07.mp3", "name" : "Blessure (1)"},
	{"id" : "HOBGOB08", "tag" : "hobgoblin", "file" : "cre/hobgl/hobgl08.mp3", "name" : "Blessure (2)"},
	{"id" : "HOBGOB09", "tag" : "hobgoblin", "file" : "cre/hobgl/hobgl09.mp3", "name" : "Mort"},
	{"id" : "HOBGOB10", "tag" : "hobgoblin", "file" : "cre/hobgl/hobgl10.mp3", "name" : "Rugissement"},

	// ===========================================================================
	// ---------------------------------------------------------------------------
	// # Cohorts
	// ---------------------------------------------------------------------------
	// ===========================================================================

	// Imoen (fixed)
	{"id" : "IMOEN01", "tag" : "imoen", "file" : "coo/imoen/imoen01.mp3", "name" : "Hé ! C'est moi, Imoen ! C'est bon de vous revoir !"},
	{"id" : "IMOEN03", "tag" : "imoen", "file" : "coo/imoen/imoen03.mp3", "name" : "Ma lame vous coupera en morceaux !"},
	{"id" : "IMOEN05", "tag" : "imoen", "file" : "coo/imoen/imoen05.mp3", "name" : "J'en ai assez !"},
	{"id" : "IMOEN06", "tag" : "imoen", "file" : "coo/imoen/imoen06.mp3", "name" : "J'me sortirai d'ici !"},
	{"id" : "IMOEN07", "tag" : "imoen", "file" : "coo/imoen/imoen07.mp3", "name" : "Je ne sais rien de plus, alors laissez-moi partir !"},
	{"id" : "IMOEN09", "tag" : "imoen", "file" : "coo/imoen/imoen09.mp3", "name" : "Je me sens un peu fatiguée..."},
	{"id" : "IMOEN10", "tag" : "imoen", "file" : "coo/imoen/imoen10.mp3", "name" : "Quel ennuiiiiii !"},
	{"id" : "IMOEN11", "tag" : "imoen", "file" : "coo/imoen/imoen11.mp3", "name" : "J'ai si froid... "},
	{"id" : "IMOEN14", "tag" : "imoen", "file" : "coo/imoen/imoen14.mp3", "name" : "Ce qui se passe est tout à fait inhabituel par ici, et je ne veux pas y prendre part."},
	{"id" : "IMOEN17", "tag" : "imoen", "file" : "coo/imoen/imoen17.mp3", "name" : "Quoi ?"},
	{"id" : "IMOEN18", "tag" : "imoen", "file" : "coo/imoen/imoen18.mp3", "name" : "Qu'est-ce que vous voulez ?"},
	{"id" : "IMOEN19", "tag" : "imoen", "file" : "coo/imoen/imoen19.mp3", "name" : "Vous êtes une bien étrange personne."},
	{"id" : "IMOEN20", "tag" : "imoen", "file" : "coo/imoen/imoen20.mp3", "name" : "Moi ? Je m'en vais."},
	{"id" : "IMOEN21", "tag" : "imoen", "file" : "coo/imoen/imoen21.mp3", "name" : "Par ici !"},
	{"id" : "IMOEN23", "tag" : "imoen", "file" : "coo/imoen/imoen23.mp3", "name" : "Voulez-vous me raconter une histoire de lutins et de fées ? S'il vous plaît !"},
	{"id" : "IMOEN24", "tag" : "imoen", "file" : "coo/imoen/imoen24.mp3", "name" : "Chez moi, Pierrot me racontait toujours une histoire..."},
	{"id" : "IMOEN27", "tag" : "imoen", "file" : "coo/imoen/imoen27.mp3", "name" : "S'il vous plaît, messieurs, je m'excuse pour ce que j'ai fait, mais il nous faut bien manger, nous les filles. "},
	{"id" : "IMOEN32", "tag" : "imoen", "file" : "coo/imoen/imoen32.mp3", "name" : "Vous êtes tous des imbéciles."},
	{"id" : "IMOEN33", "tag" : "imoen", "file" : "coo/imoen/imoen33.mp3", "name" : "Espèce de racaille !"},
	{"id" : "IMOEN35", "tag" : "imoen", "file" : "coo/imoen/imoen35.mp3", "name" : "Que Dieu vous garde si vous réussissez."},
	{"id" : "IMOEN38", "tag" : "imoen", "file" : "coo/imoen/imoen38.mp3", "name" : "Blessure"},
	{"id" : "IMOEN39", "tag" : "imoen", "file" : "coo/imoen/imoen39.mp3", "name" : "Mort"},
	{"id" : "IMOEN40", "tag" : "imoen", "file" : "coo/imoen/imoen40.mp3", "name" : "Pauvre chose, connaître la mort si tôt."},
	// Garrick (fixed)
	{"id" : "GARRICK01", "tag" : "garrick", "file" : "coo/garrk/garrk01.mp3", "name" : "Salut la compagnie. J'ai une offre à vous faire."},
	{"id" : "GARRICK02", "tag" : "garrick", "file" : "coo/garrk/garrk02.mp3", "name" : "Ce brave, très brave, sire Garrick, montrait le chemin. Et ce brave, très brave, sire Garrick, s'est enfui très loin."},
	{"id" : "GARRICK03", "tag" : "garrick", "file" : "coo/garrk/garrk03.mp3", "name" : "Le sort en est jeté, chers amis !"},
	{"id" : "GARRICK04", "tag" : "garrick", "file" : "coo/garrk/garrk04.mp3", "name" : "Si la valeur d'un homme se mesure à sa civilité, alors je passerai pour une célébrité."},
	{"id" : "GARRICK05", "tag" : "garrick", "file" : "coo/garrk/garrk05.mp3", "name" : "Mais pourquoi avons-nous agi de la sorte ?"},
	{"id" : "GARRICK06", "tag" : "garrick", "file" : "coo/garrk/garrk06.mp3", "name" : "Je ne peux pas attendre que ça se passe sans réagir."},
	{"id" : "GARRICK07", "tag" : "garrick", "file" : "coo/garrk/garrk07.mp3", "name" : "Désolé, mais je dois partir. Je ne peux plus tolérer nos agissements."},
	{"id" : "GARRICK08", "tag" : "garrick", "file" : "coo/garrk/garrk08.mp3", "name" : "Je me sens mal préparé à cette tâche, mais je ferai de mon mieux. "},
	{"id" : "GARRICK09", "tag" : "garrick", "file" : "coo/garrk/garrk09.mp3", "name" : "-baille- Un bâillement est un cri silencieux."},
	{"id" : "GARRICK10", "tag" : "garrick", "file" : "coo/garrk/garrk10.mp3", "name" : "Un homme qui s'ennuie est un homme en colère."},
	{"id" : "GARRICK11", "tag" : "garrick", "file" : "coo/garrk/garrk11.mp3", "name" : "Seigneur, je crois que je me meurs..."},
	{"id" : "GARRICK12", "tag" : "garrick", "file" : "coo/garrk/garrk12.mp3", "name" : "Je crois que jamais un poème ne sera aussi joli qu'un arbre."},
	{"id" : "GARRICK13", "tag" : "garrick", "file" : "coo/garrk/garrk13.mp3", "name" : "Il fait une journée magnifique dans le coin. "},
	{"id" : "GARRICK17", "tag" : "garrick", "file" : "coo/garrk/garrk17.mp3", "name" : "Oui monsieur ?"},
	{"id" : "GARRICK18", "tag" : "garrick", "file" : "coo/garrk/garrk18.mp3", "name" : "Je suis à votre service."},
	{"id" : "GARRICK19", "tag" : "garrick", "file" : "coo/garrk/garrk19.mp3", "name" : "La vie est merveilleuse. "},
	{"id" : "GARRICK20", "tag" : "garrick", "file" : "coo/garrk/garrk20.mp3", "name" : "Sur-le-champ."},
	{"id" : "GARRICK21", "tag" : "garrick", "file" : "coo/garrk/garrk21.mp3", "name" : "Avec l'aide de dieu."},
	{"id" : "GARRICK22", "tag" : "garrick", "file" : "coo/garrk/garrk22.mp3", "name" : "Avec joie, monsieur."},
	{"id" : "GARRICK23", "tag" : "garrick", "file" : "coo/garrk/garrk23.mp3", "name" : "Distribuez, dépensez... les Dieux pourvoiront."},
	{"id" : "GARRICK24", "tag" : "garrick", "file" : "coo/garrk/garrk24.mp3", "name" : "Réduisez les distances à parcourir en paroles et en rires."},
	{"id" : "GARRICK25", "tag" : "garrick", "file" : "coo/garrk/garrk25.mp3", "name" : "C'est l'amour qui fait tourner le monde."},
	{"id" : "GARRICK26", "tag" : "garrick", "file" : "coo/garrk/garrk26.mp3", "name" : "La musique possède le don d'apaiser les cours rebelles."},
	{"id" : "GARRICK27", "tag" : "garrick", "file" : "coo/garrk/garrk27.mp3", "name" : "Skie, peut-être aimeriez-vous écouter ma musique ? Elle est très différente, meilleure même, que celle d'Eldoth."},
	{"id" : "GARRICK28", "tag" : "garrick", "file" : "coo/garrk/garrk28.mp3", "name" : "Pourquoi rester avec Eldoth, Skie ? Ne voyez-vous pas qu'il se sert de vous ?"},
	{"id" : "GARRICK29", "tag" : "garrick", "file" : "coo/garrk/garrk29.mp3", "name" : "Ne parlez pas ainsi à Skie, Eldoth. Elle mérite mieux."},
	{"id" : "GARRICK30", "tag" : "garrick", "file" : "coo/garrk/garrk30.mp3", "name" : "Ma musique est meilleure que la vôtre, Eldoth. J'ai appris à jouer au collège de Berdusk."},
	{"id" : "GARRICK31", "tag" : "garrick", "file" : "coo/garrk/garrk31.mp3", "name" : "Une jolie fille est un gage de bonheur éternel."},
	{"id" : "GARRICK32", "tag" : "garrick", "file" : "coo/garrk/garrk32.mp3", "name" : "Merci infiniment pour ce superbe compliment."},
	{"id" : "GARRICK33", "tag" : "garrick", "file" : "coo/garrk/garrk33.mp3", "name" : "Je ne sais pas ce que j'ai fait pour mériter ça."},
	{"id" : "GARRICK34", "tag" : "garrick", "file" : "coo/garrk/garrk34.mp3", "name" : "Il faut être deux pour se battre."},
	{"id" : "GARRICK35", "tag" : "garrick", "file" : "coo/garrk/garrk35.mp3", "name" : "Je pense que vous êtes quelqu'un d'honorable."},
	{"id" : "GARRICK36", "tag" : "garrick", "file" : "coo/garrk/garrk36.mp3", "name" : "Je n'ai jamais rencontré quelqu'un d'aussi prévenant. "},
	{"id" : "GARRICK37", "tag" : "garrick", "file" : "coo/garrk/garrk37.mp3", "name" : "Je crois qu'il vous faut apprendre les bonnes manières."},
	{"id" : "GARRICK38", "tag" : "garrick", "file" : "coo/garrk/garrk38.mp3", "name" : "Blessure"},
	{"id" : "GARRICK39", "tag" : "garrick", "file" : "coo/garrk/garrk39.mp3", "name" : "Mort"},
	{"id" : "GARRICK40", "tag" : "garrick", "file" : "coo/garrk/garrk40.mp3", "name" : "Le monde est bien cruel."},
	{"id" : "GARRICK41", "tag" : "garrick", "file" : "coo/garrk/garrk41.mp3", "name" : "Nooon. Pourquoi elle ? Elle ne méritait pas ça !!!"},
	// Kagain (fixed)
	{"id" : "KAGAIN01", "tag" : "kagain", "file" : "coo/kagan/kagan01.mp3", "name" : "Mes hommages, je m'appelle Kagain, que puis-je faire pour vous ?"},
	{"id" : "KAGAIN02", "tag" : "kagain", "file" : "coo/kagan/kagan02.mp3", "name" : "Il n'y a pas de quoi risquer sa vie."},
	{"id" : "KAGAIN03", "tag" : "kagain", "file" : "coo/kagan/kagan03.mp3", "name" : "Par amour de l'argent."},
	{"id" : "KAGAIN05", "tag" : "kagain", "file" : "coo/kagan/kagan05.mp3", "name" : "Espèces d'imbéciles, que faisiez-vous là ?"},
	{"id" : "KAGAIN06", "tag" : "kagain", "file" : "coo/kagan/kagan06.mp3", "name" : "Les gens pleins de bonnes intentions me donnent la nausée."},
	{"id" : "KAGAIN07", "tag" : "kagain", "file" : "coo/kagan/kagan07.mp3", "name" : "Et voilà, le nain s'en va."},
	{"id" : "KAGAIN08", "tag" : "kagain", "file" : "coo/kagan/kagan08.mp3", "name" : "En tant que chef, j'entends faire de nous des gens bourrés d'argent."},
	{"id" : "KAGAIN09", "tag" : "kagain", "file" : "coo/kagan/kagan09.mp3", "name" : "Tout nain qu'il est, y'a des limites à son endurance."},
	{"id" : "KAGAIN10", "tag" : "kagain", "file" : "coo/kagan/kagan10.mp3", "name" : "C'est pas en restant là qu'on va devenir riches."},
	{"id" : "KAGAIN11", "tag" : "kagain", "file" : "coo/kagan/kagan11.mp3", "name" : "Le nain se sent pas très bien."},
	{"id" : "KAGAIN12", "tag" : "kagain", "file" : "coo/kagan/kagan12.mp3", "name" : "Foutue forêt, elle me fait toujours penser à ces femmelettes d'elfes..."},
	{"id" : "KAGAIN14", "tag" : "kagain", "file" : "coo/kagan/kagan14.mp3", "name" : "J'aime cet endroit, qui regorge d'or."},
	{"id" : "KAGAIN17", "tag" : "kagain", "file" : "coo/kagan/kagan17.mp3", "name" : "Je veux pas parler."},
	{"id" : "KAGAIN18", "tag" : "kagain", "file" : "coo/kagan/kagan18.mp3", "name" : "Allez enquiquiner quelqu'un d'autre."},
	{"id" : "KAGAIN19", "tag" : "kagain", "file" : "coo/kagan/kagan19.mp3", "name" : "Il me faut une bière."},
	{"id" : "KAGAIN20", "tag" : "kagain", "file" : "coo/kagan/kagan20.mp3", "name" : "-rot- Bien sûr."},
	{"id" : "KAGAIN21", "tag" : "kagain", "file" : "coo/kagan/kagan21.mp3", "name" : "D'accord."},
	{"id" : "KAGAIN22", "tag" : "kagain", "file" : "coo/kagan/kagan22.mp3", "name" : "Pourquoi moi ?"},
	{"id" : "KAGAIN23", "tag" : "kagain", "file" : "coo/kagan/kagan23.mp3", "name" : "Le seul truc qui soit mieux que de l'or... c'est encore plus d'or."},
	{"id" : "KAGAIN24", "tag" : "kagain", "file" : "coo/kagan/kagan24.mp3", "name" : "Vous commencez à me porter sur les nerfs."},
	{"id" : "KAGAIN25", "tag" : "kagain", "file" : "coo/kagan/kagan25.mp3", "name" : "C'est l'or qui fait tourner le monde. Plus on le sait tôt, mieux on s'en sort."},
	{"id" : "KAGAIN26", "tag" : "kagain", "file" : "coo/kagan/kagan26.mp3", "name" : "Si j'avais gagné une petite pièce pour chaque crétin rencontré, je pourrais me payer la Porte de Baldur."},
	{"id" : "KAGAIN27", "tag" : "kagain", "file" : "coo/kagan/kagan27.mp3", "name" : "J'ai jamais rencontré un nain aussi bête. T'es une honte pour les nains du monde entier."},
	{"id" : "KAGAIN28", "tag" : "kagain", "file" : "coo/kagan/kagan28.mp3", "name" : "Yeslick, c'est vot' bêtise qui a causé tous ces ennuis."},
	{"id" : "KAGAIN29", "tag" : "kagain", "file" : "coo/kagan/kagan29.mp3", "name" : "Yeslick, fermez votre grande goule et disparaissez !"},
	{"id" : "KAGAIN30", "tag" : "kagain", "file" : "coo/kagan/kagan30.mp3", "name" : "Vous êtes un imbécile, Yeslick. Si vous continuez à m'énerver, je vous arrache la tête !"},
	{"id" : "KAGAIN31", "tag" : "kagain", "file" : "coo/kagan/kagan31.mp3", "name" : "Quelle excuse indigne d'un nain ! Approchez que je vous botte le derrière !"},
	{"id" : "KAGAIN32", "tag" : "kagain", "file" : "coo/kagan/kagan32.mp3", "name" : "Vous feriez mieux de vous taire."},
	{"id" : "KAGAIN33", "tag" : "kagain", "file" : "coo/kagan/kagan33.mp3", "name" : "Continuez à parler comme ça et j'vais vous remplir la bouche de bouse de vache !"},
	{"id" : "KAGAIN34", "tag" : "kagain", "file" : "coo/kagan/kagan34.mp3", "name" : "Taisez-vous et montrez-moi les pépètes !"},
	{"id" : "KAGAIN35", "tag" : "kagain", "file" : "coo/kagan/kagan35.mp3", "name" : "Eh, vous vous croyez où là ?!!"},
	{"id" : "KAGAIN36", "tag" : "kagain", "file" : "coo/kagan/kagan36.mp3", "name" : "Espèce d'altruiste !"},
	{"id" : "KAGAIN37", "tag" : "kagain", "file" : "coo/kagan/kagan37.mp3", "name" : "Espèce d'imbécile, fermez-la, vous allez avoir des ennuis !"},
	{"id" : "KAGAIN38", "tag" : "kagain", "file" : "coo/kagan/kagan38.mp3", "name" : "Blessure"},
	{"id" : "KAGAIN39", "tag" : "kagain", "file" : "coo/kagan/kagan39.mp3", "name" : "Mort"},
	{"id" : "KAGAIN40", "tag" : "kagain", "file" : "coo/kagan/kagan40.mp3", "name" : "Plutôt eux que moi."},
	{"id" : "KAGAIN41", "tag" : "kagain", "file" : "coo/kagan/kagan41.mp3", "name" : "Tôt ou tard, il fallait bien que cet avorton y passe..."},
	// KIVAN (fixed)
	{"id" : "KIVAN01", "tag" : "kivan", "file" : "coo/kivan/kivan01.mp3", "name" : "Holà ! C'est bien rare de rencontrer des étrangers dans cette partie du monde."},
	{"id" : "KIVAN02", "tag" : "kivan", "file" : "coo/kivan/kivan02.mp3", "name" : "Battez donc en retraite, nous n'avons aucune chance de vaincre."},
	{"id" : "KIVAN03", "tag" : "kivan", "file" : "coo/kivan/kivan03.mp3", "name" : "En avant !"},
	{"id" : "KIVAN04", "tag" : "kivan", "file" : "coo/kivan/kivan04.mp3", "name" : "C'est une action des plus nobles."},
	{"id" : "KIVAN05", "tag" : "kivan", "file" : "coo/kivan/kivan05.mp3", "name" : "Je n'apprécie guère la ligne de conduite adoptée."},
	{"id" : "KIVAN06", "tag" : "kivan", "file" : "coo/kivan/kivan06.mp3", "name" : "Je ne tolérerai plus un tel comportement ."},
	{"id" : "KIVAN07", "tag" : "kivan", "file" : "coo/kivan/kivan07.mp3", "name" : "Je ne peux pas permettre que cela continue. Défendez-vous."},
	{"id" : "KIVAN08", "tag" : "kivan", "file" : "coo/kivan/kivan08.mp3", "name" : "Je resterai à la tête du groupe aussi longtemps qu'il le faudra."},
	{"id" : "KIVAN09", "tag" : "kivan", "file" : "coo/kivan/kivan09.mp3", "name" : "Il est temps de nous reposer."},
	{"id" : "KIVAN10", "tag" : "kivan", "file" : "coo/kivan/kivan10.mp3", "name" : "Nous avons perdu suffisamment de temps."},
	{"id" : "KIVAN11", "tag" : "kivan", "file" : "coo/kivan/kivan11.mp3", "name" : "Je ne sais pas combien de temps je vais encore tenir."},
	{"id" : "KIVAN13", "tag" : "kivan", "file" : "coo/kivan/kivan13.mp3", "name" : "Cette ville est un exemple des abus humains. Je voudrais avoir quitté ce misérable endroit."},
	{"id" : "KIVAN14", "tag" : "kivan", "file" : "coo/kivan/kivan14.mp3", "name" : "Pourquoi imiter les manières de ces nabots qui rampent par ces terriers."},
	{"id" : "KIVAN17", "tag" : "kivan", "file" : "coo/kivan/kivan17.mp3", "name" : "Oui ?"},
	{"id" : "KIVAN18", "tag" : "kivan", "file" : "coo/kivan/kivan18.mp3", "name" : "Que voulez-vous ?"},
	{"id" : "KIVAN19", "tag" : "kivan", "file" : "coo/kivan/kivan19.mp3", "name" : "Laissez-moi tranquille."},
	{"id" : "KIVAN20", "tag" : "kivan", "file" : "coo/kivan/kivan20.mp3", "name" : "-grognement-"},
	{"id" : "KIVAN21", "tag" : "kivan", "file" : "coo/kivan/kivan21.mp3", "name" : "Comme vous voudrez"},
	{"id" : "KIVAN22", "tag" : "kivan", "file" : "coo/kivan/kivan22.mp3", "name" : "Oui."},
	{"id" : "KIVAN23", "tag" : "kivan", "file" : "coo/kivan/kivan23.mp3", "name" : "L'heure n'est pas aux bavardages."},
	{"id" : "KIVAN24", "tag" : "kivan", "file" : "coo/kivan/kivan24.mp3", "name" : "Mon âme porte le deuil de ma Deheriana."},
	{"id" : "KIVAN25", "tag" : "kivan", "file" : "coo/kivan/kivan25.mp3", "name" : "Ne perdons pas de temps en palabres."},
	{"id" : "KIVAN26", "tag" : "kivan", "file" : "coo/kivan/kivan26.mp3", "name" : "Ma soif de vengeance me donne la force de poursuivre."},
	{"id" : "KIVAN27", "tag" : "kivan", "file" : "coo/kivan/kivan27.mp3", "name" : "Ne m'approchez pas, elfe noir."},
	{"id" : "KIVAN28", "tag" : "kivan", "file" : "coo/kivan/kivan28.mp3", "name" : "Comment pourrions-nous faire confiance à un adorateur de la Reine Araignée ?"},
	{"id" : "KIVAN29", "tag" : "kivan", "file" : "coo/kivan/kivan29.mp3", "name" : "Votre malignité vous perdra, elfe noir."},
	{"id" : "KIVAN30", "tag" : "kivan", "file" : "coo/kivan/kivan30.mp3", "name" : "C'est mon dernier avertissement, Drow. La prochaine fois, je vous tuerai !"},
	{"id" : "KIVAN31", "tag" : "kivan", "file" : "coo/kivan/kivan31.mp3", "name" : "Espèce de garce maléfique, je vais vous tuer !"},
	{"id" : "KIVAN32", "tag" : "kivan", "file" : "coo/kivan/kivan32.mp3", "name" : "Faites attention à ce que vous dites..."},
	{"id" : "KIVAN33", "tag" : "kivan", "file" : "coo/kivan/kivan33.mp3", "name" : "Taisez-vous !"},
	{"id" : "KIVAN34", "tag" : "kivan", "file" : "coo/kivan/kivan34.mp3", "name" : "J'apprécie votre franchise."},
	{"id" : "KIVAN35", "tag" : "kivan", "file" : "coo/kivan/kivan35.mp3", "name" : "Vous êtes un compagnon très précieux."},
	{"id" : "KIVAN36", "tag" : "kivan", "file" : "coo/kivan/kivan36.mp3", "name" : "Votre courage fait honte aux autres."},
	{"id" : "KIVAN37", "tag" : "kivan", "file" : "coo/kivan/kivan37.mp3", "name" : "Taisez-vous, vos bavardages vont nous rendre fous."},
	{"id" : "KIVAN38", "tag" : "kivan", "file" : "coo/kivan/kivan38.mp3", "name" : "Blessure"},
	{"id" : "KIVAN39", "tag" : "kivan", "file" : "coo/kivan/kivan39.mp3", "name" : "Mort"},
	{"id" : "KIVAN40", "tag" : "kivan", "file" : "coo/kivan/kivan40.mp3", "name" : "Encore un compagnon que nous regretterons."},
	{"id" : "KIVAN41", "tag" : "kivan", "file" : "coo/kivan/kivan41.mp3", "name" : "Puisse l'âme de Viconia pourrir en enfer."},
	// AJANTIS (fixed)
	{"id" : "AJANT01", "tag" : "ajantis", "file" : "coo/ajant/ajant01.mp3", "name" : "Halte-là, dans quel camp êtes-vous ?"},
	{"id" : "AJANT02", "tag" : "ajantis", "file" : "coo/ajant/ajant02.mp3", "name" : "Quelle lâcheté ! Allez rejoindre ceux qui vous réclament."},
	{"id" : "AJANT03", "tag" : "ajantis", "file" : "coo/ajant/ajant03.mp3", "name" : "Pour la gloire de Heaum !"},
	{"id" : "AJANT04", "tag" : "ajantis", "file" : "coo/ajant/ajant04.mp3", "name" : "Nous suivons la voie de la vertu, celle de Heaum."},
	{"id" : "AJANT05", "tag" : "ajantis", "file" : "coo/ajant/ajant05.mp3", "name" : "Le chemin que nous suivons nous détourne de la moralité."},
	{"id" : "AJANT06", "tag" : "ajantis", "file" : "coo/ajant/ajant06.mp3", "name" : "Je refuse d'assister à la dépravation de notre groupe."},
	{"id" : "AJANT07", "tag" : "ajantis", "file" : "coo/ajant/ajant07.mp3", "name" : "C'en est fait de tant de méchanceté ! Dégainez votre épée et mettons un terme à ce différend une fois pour toutes !"},
	{"id" : "AJANT08", "tag" : "ajantis", "file" : "coo/ajant/ajant08.mp3", "name" : "La responsabilité que vous me confiez m'honore."},
	{"id" : "AJANT09", "tag" : "ajantis", "file" : "coo/ajant/ajant09.mp3", "name" : "Je commence à perdre patience, hein !"},
	{"id" : "AJANT10", "tag" : "ajantis", "file" : "coo/ajant/ajant10.mp3", "name" : "Nous avons le devoir de combattre le mal. Ne perdons pas de temps en futilités ! "},
	{"id" : "AJANT11", "tag" : "ajantis", "file" : "coo/ajant/ajant11.mp3", "name" : "Haaa ... J'ai besoin d'aide."},
	{"id" : "AJANT12", "tag" : "ajantis", "file" : "coo/ajant/ajant12.mp3", "name" : "Cette forêt ne laisse rien présager de très bon."},
	{"id" : "AJANT13", "tag" : "ajantis", "file" : "coo/ajant/ajant13.mp3", "name" : "Cette ville ne laisse rien présager de très bon."},
	{"id" : "AJANT14", "tag" : "ajantis", "file" : "coo/ajant/ajant14.mp3", "name" : "Ce donjon ne laisse rien présager de très bon."},
	{"id" : "AJANT17", "tag" : "ajantis", "file" : "coo/ajant/ajant17.mp3", "name" : "Je vis pour l'honneur."},
	{"id" : "AJANT18", "tag" : "ajantis", "file" : "coo/ajant/ajant18.mp3", "name" : "Heaum, donnez-moi la force de poursuivre."},
	{"id" : "AJANT19", "tag" : "ajantis", "file" : "coo/ajant/ajant19.mp3", "name" : "Par Heaum !"},
	{"id" : "AJANT20", "tag" : "ajantis", "file" : "coo/ajant/ajant20.mp3", "name" : "Comme vous voudrez."},
	{"id" : "AJANT21", "tag" : "ajantis", "file" : "coo/ajant/ajant21.mp3", "name" : "Avec la bénédiction de Heaum."},
	{"id" : "AJANT22", "tag" : "ajantis", "file" : "coo/ajant/ajant22.mp3", "name" : "Oui."},
	{"id" : "AJANT23", "tag" : "ajantis", "file" : "coo/ajant/ajant23.mp3", "name" : "Nous devons nous efforcer de montrer l'exemple aux plus faibles."},
	{"id" : "AJANT24", "tag" : "ajantis", "file" : "coo/ajant/ajant24.mp3", "name" : "Rien n'importe plus que le sens du devoir."},
	{"id" : "AJANT25", "tag" : "ajantis", "file" : "coo/ajant/ajant25.mp3", "name" : "Le courage et le sens de l'honneur vaincront toujours le mal."},
	{"id" : "AJANT26", "tag" : "ajantis", "file" : "coo/ajant/ajant26.mp3", "name" : "Le mal doit être anéanti sans pitié."},
	{"id" : "AJANT27", "tag" : "ajantis", "file" : "coo/ajant/ajant27.mp3", "name" : "Vos actions sont une offense aux préceptes de Heaum.  "},
	{"id" : "AJANT28", "tag" : "ajantis", "file" : "coo/ajant/ajant28.mp3", "name" : "On appartient soit aux forces du bien soit à celles du mal, et je vous soupçonne d'appartenir à celles du mal."},
	{"id" : "AJANT29", "tag" : "ajantis", "file" : "coo/ajant/ajant29.mp3", "name" : "Le mal doit être éliminé où qu'il soit, même parmi nos amis."},
	{"id" : "AJANT30", "tag" : "ajantis", "file" : "coo/ajant/ajant30.mp3", "name" : "La cruauté qui vous anime est abominable."},
	{"id" : "AJANT31", "tag" : "ajantis", "file" : "coo/ajant/ajant31.mp3", "name" : "Je n'en supporterai pas davantage. Sortez votre arme et défendez-vous !"},
	{"id" : "AJANT32", "tag" : "ajantis", "file" : "coo/ajant/ajant32.mp3", "name" : "Attention à ce que vous dites devant la gent féminine !"},
	{"id" : "AJANT34", "tag" : "ajantis", "file" : "coo/ajant/ajant34.mp3", "name" : "Merci du compliment"},
	{"id" : "AJANT35", "tag" : "ajantis", "file" : "coo/ajant/ajant35.mp3", "name" : "Vous êtes d'une grande beauté, mademoiselle."},
	{"id" : "AJANT36", "tag" : "ajantis", "file" : "coo/ajant/ajant36.mp3", "name" : "Vous êtes un homme d'honneur, et je respecte votre intégrité."},
	{"id" : "AJANT37", "tag" : "ajantis", "file" : "coo/ajant/ajant37.mp3", "name" : "Il serait sage de changer vos manières tant que vous serez parmi nous."},
	{"id" : "AJANT38", "tag" : "ajantis", "file" : "coo/ajant/ajant38.mp3", "name" : "Blessure"},
	{"id" : "AJANT39", "tag" : "ajantis", "file" : "coo/ajant/ajant39.mp3", "name" : "Mort"},
	{"id" : "AJANT40", "tag" : "ajantis", "file" : "coo/ajant/ajant40.mp3", "name" : "Réjouissons-nous que notre compagnon soit tombé pour une cause juste. "},
	{"id" : "AJANT41", "tag" : "ajantis", "file" : "coo/ajant/ajant41.mp3", "name" : "Il est bien malheureux que notre compagnon soit mort avant d'avoir eu le temps de se racheter."},
];
